### ISSUE TITLE
docker本地部署运行gpt3.5报错：{"_action":"_ask","error":"an error occurred timed out","success":false}

### ISSUE THREAD

**Issue by 2424004764** [ramonvc/freegpt-webui#116]
![image](https://github.com/ramonvc/freegpt-webui/assets/24261680/cd76dca2-8fb0-4e9c-8ac5-2075371afe37)

**Comment by ramonvc** [comment]
Duplicate issues https://github.com/ramonvc/freegpt-webui/issues/113
