### ISSUE TITLE
Rate limit reached for gpt-4! Please, try again in xxx seconds!

### ISSUE THREAD

**Issue by allentofight** [ramonvc/freegpt-webui#124]
when i  call gpt4, it always reports this error

**Comment by ramonvc** [comment]
In the [chimera version](https://github.com/ramonvc/freegpt-webui/tree/chimeragpt-version) you need to use a free API to unlock all models and limits. 
Or use the [standard version](https://freegpt-webui.ramonvc.repl.co/chat/) with no API needed.

**Comment by allentofight** [comment]
> free API

how to get the free API

**Comment by ramonvc** [comment]
> > free API
> 
> how to get the free API

on [discord ChimeraGPT](https://discord.com/invite/eStXUJEZn4)
