### ISSUE TITLE
How to activate web search

### ISSUE THREAD

**Issue by Rizaldy** [ramonvc/freegpt-webui#125]
First of all, hats off to the team for a very well done projects! I used the chimera tree and get the chimera API from discord and it's just works.

I've been searching to all issues and discussion but cannot find on how to activate web browser and jailbreak function. Sorry if it's already covered before

<img width="1296" alt="image" src="https://github.com/ramonvc/freegpt-webui/assets/7367220/a1a59df1-92ac-4f20-a3e0-0ce1e4af984d">
As the image above, the web access toggle is is on, but when I asked it still not using the search function.

in backend.py I see
```
# Add web results if enabled
    if internet_access:
        current_date = datetime.now().strftime("%Y-%m-%d")
        query = f'Current date: {current_date}. ' + prompt["content"]
        search_results = fetch_search_results(query)
        conversation.extend(search_results)

    # Add jailbreak instructions if enabled
    if jailbreak_instructions := getJailbreak(jailbreak):
        conversation.extend(jailbreak_instructions)
```

but still cannot find how to activate it. Thanks in advance!

**Comment by ramonvc** [comment]
> First of all, hats off to the team for a very well done projects! I used the chimera tree and get the chimera API from discord and it's just works.
> 
> I've been searching to all issues and discussion but cannot find on how to activate web browser and jailbreak function. Sorry if it's already covered before
> 
> <img alt="image" width="1296" src="https://user-images.githubusercontent.com/7367220/254637187-a1a59df1-92ac-4f20-a3e0-0ce1e4af984d.png"> As the image above, the web access toggle is is on, but when I asked it still not using the search function.
> in backend.py I see
> 
> ```
> # Add web results if enabled
>     if internet_access:
>         current_date = datetime.now().strftime("%Y-%m-%d")
>         query = f'Current date: {current_date}. ' + prompt["content"]
>         search_results = fetch_search_results(query)
>         conversation.extend(search_results)
> 
>     # Add jailbreak instructions if enabled
>     if jailbreak_instructions := getJailbreak(jailbreak):
>         conversation.extend(jailbreak_instructions)
> ```
> 
> but still cannot find how to activate it. Thanks in advance!

Both web search and jailbreak are added along with the user prompt so the model would recognize the instructions and follow them. However, OpenAI is creating multiple rules, which makes the model not even recognize the web search.

[The performance of GPT-4 has greatly decreased because of rules](https://twitter.com/svpino/status/1681614284613099520?s=19)
