### ISSUE TITLE
{"_action":"_ask","error":"an error occurred timed out","success":false}

### ISSUE THREAD

**Issue by liuyang77886** [ramonvc/freegpt-webui#13]
我使用的是 docker run -p 1338:1338 ramonvc/freegpt-webui 构建的环境
对话后显示  
{"_action":"_ask","error":"an error occurred timed out","success":false}

**Comment by ramonvc** [comment]
This error occurs when the GPT response API is unstable. 

To address this issue, I made a change in which, if there is an error in the API response, it will attempt to obtain the response 2 more times. https://github.com/ramonvc/freegpt-webui/commit/720c1cf240e8e7f66bfeef1a4d5cf43999fb0e74

If this happens all the time, your connection might be blocking the API. In this case, the ideal would be to use a Proxy or VPN.

**Comment by cethink** [comment]
I got this error too and I had set `"use_auto_proxy": true`

**Comment by huangxiaopia** [comment]
我也发生了这个问题
