### ISSUE TITLE
claude系列咋用不了  可以加一个导出对话的功能吗

### ISSUE THREAD

**Issue by clint-sfy** [ramonvc/freegpt-webui#135]
HTTP code 502 from API (<html> <head><title>502 Bad Gateway</title></head> <body> <center><h1>502 Bad Gateway</h1></center> <hr><center>nginx/1.18.0 (Ubuntu)</center> </body> </html> )

**Comment by ramonvc** [comment]
This happens when the Chimera API is down for maintenance.
