### ISSUE TITLE
How to add login and password authentication to a freegpt VPS server?

### ISSUE THREAD

**Issue by wedcanto** [ramonvc/freegpt-webui#138]
Hello! After launching freegpt on a VPS server, it is accessible to everyone on the internet at the address my_ip:1338. How can I make it prompt for a login and password when opening the page in a browser? Ideally, it would be possible to separate different users (grant access to friends).

**Comment by ramonvc** [comment]
Need to create a way of authentication. 
It can be done in different ways. From simpler using Nginx, or a little more complex and robust with Auth0. 

There are many ways.
