### ISSUE TITLE
 "POST /backend-api/v2/conversation HTTP/1.1" 400 -

### ISSUE THREAD

**Issue by MrJingLiguo** [ramonvc/freegpt-webui#14]
"POST /backend-api/v2/conversation HTTP/1.1" 400 -

**Comment by ramonvc** [comment]
Unfortunately, I cannot help you with just this information. If you could provide more context about when this error occurred and a log, it may help me identify the problem.

**Comment by MrJingLiguo** [comment]
![image](https://github.com/ramonvc/freegpt-webui/assets/76695033/9e70ec45-3bc9-4650-ab7a-4eaa56053295)

**Comment by cjyzwg** [comment]
I also encouter problem like this

{"_action":"_ask","error":"an error occurred [Errno 99] Cannot assign requested address","success":false}

**Comment by d-serafly** [comment]
I have a similar problem. I use an additional VPN but still have the same problem; in the off answer, this appears to be a connection problem? Will this always be the case?

**Comment by bashamahmoud** [comment]
I have same problem. for me it happens when I enter a very long prompt aka huge code

**Comment by haihaolei** [comment]
I have same problem.
![image](https://github.com/ramonvc/freegpt-webui/assets/52911491/c8ec724e-2a8a-4a9a-90b7-66381fbdee9c)
![image](https://github.com/ramonvc/freegpt-webui/assets/52911491/6223c7d2-1fda-4eed-829d-f52b526ec49a)

**Comment by MrJingLiguo** [comment]
I got it running normally on another computer with three special requests that were proxed through the VPN

**Comment by Cmysession** [comment]
@haihaolei 你是不是用了节点或VPN,换一个节点或VPN

**Comment by Cmysession** [comment]
我想问下,我想把这个项目对接到我的项目里去,我用postman测试post请求 返回 Connection closed ,作者是否可以优化下,我们好可以自己post请求,方便扩展

**Comment by koko-lin** [comment]
我想问下,我架设的服务经常出现400错误,返回{"_action":"_ask","error":"an error occurred string indices must be integers","success":false},请问是什么问题,怎么解决?
