### ISSUE TITLE
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application

### ISSUE THREAD

**Issue by owenskydev** [ramonvc/freegpt-webui#146]
Hello everyone.

Only GPT-3.5 and GPT-4 works.
Otherwise I get an error: 
<!doctype html> <html lang=en> <title>500 Internal Server Error</title> <h1>Internal Server Error</h1> <p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>

Initially everything was working fine until I tried the xtekky's repository.
After that since yesterday I am getting the error.
People have similar problem with all versions, but I only have it with 0613, turbo16k, turbo16k-0613.
 
Web access works too, sometimes a bit incorrectly, but it still works if you ask the right questions.
At least something works, but I'd like to fix the issues anyway. 
![1](https://github.com/ramonvc/freegpt-webui/assets/139978185/28147ecc-9108-4e06-ae5a-4674e538b714)
![2](https://github.com/ramonvc/freegpt-webui/assets/139978185/d4f51e0a-0cad-4fae-9b26-49d7895e6473)
![3](https://github.com/ramonvc/freegpt-webui/assets/139978185/776cf226-da6e-41f8-914e-c15a1337912b)

**Comment by ramonvc** [comment]
Fixed: https://github.com/ramonvc/freegpt-webui/commit/85809dc12c72d440dde3b83f18ff24d5f4374cb6

**Comment by owenskydev** [comment]
What is the best model to use with and without web access
I don't understand the difference. Is there a difference?
