### ISSUE TITLE
[bug] main branch of commit 85809dc is not working correctly

### ISSUE THREAD

**Issue by StoneLyu** [ramonvc/freegpt-webui#148]
`git pull` 85809dc about 1 hour ago, when I typed some message and click `send` button, the message is not sent and is still remaining in the input area, and no response in the conversion area.
refresh several times, but it's still not working.

Then I tried to `git checkout chimeragpt-version`, the `send button` works good.

**Comment by ramonvc** [comment]
In this commit nothing of the UI was changed, only the GPT-3.5-16k API model and provider.

here it is working. 

![Screenshot_20230725_020037_Samsung Internet.jpg](https://github.com/ramonvc/freegpt-webui/assets/13617054/947c44c1-96c7-4564-978a-ffada682c9f1)
