### ISSUE TITLE
GPT4 providing same result as GPT3.5

### ISSUE THREAD

**Issue by TommyTunaToro** [ramonvc/freegpt-webui#15]
Hola, amigo! Impressive work! I couldn't get g4a to work and glad to see your repo.

One thing I found weird is that I checked your code which you already fixed that "always stays on gpt4" problem. Now we can switch between 3.5 and 4. However, it is showing the same result. Since I do not have a gpt4 access, can you try this problem for me?

"""
I have a box that can only transform coins, nothing else. If you insert a number of coins into it, the next day each coin will turn into 2 apples. Thus, if you add 3 coins there will be 6 apples after one day and 0 coins. I add 10 coins and wait for 3 days. What will happen?
"""

I switched 4 and 3.5 back and forth and they all are giving me the same result, 80 apples, which is wrong. The correct answer should be 20. I have seen other people implemented this and got succussed in GPT4. 

Fully understand that it should be a forefront provider issue. How can we fix that tho? It will be quite pointless if this webhost is using 3.5 right? because everyone got access to 3.5. Or maybe not everyone but certainly everyone who is able to get on this github lol

**Comment by ramonvc** [comment]
Yes, as you mentioned, it's a forefront provider issue. For a while, I used this API in my project: [gpt4free-ts](https://github.com/xiangsx/gpt4free-ts), 
and it did create accounts with temporary emails and used them with the forefront GPT-4. However, it was very unstable in stream mode and caused a lot of problems. I'm waiting for the APIs to become more stable and even considering implementing other models, such as Alpaca 100k.
