### ISSUE TITLE
not working anymore, FileNotFoundError CreateProcess(executable... ) and Create_babel(app)

### ISSUE THREAD

**Issue by LeCarts** [ramonvc/freegpt-webui#153]
I'm not sure if this problem is due to my configuration. Today I updated the files and dependencies, I get the error shown in the image. I restored previous versions and found that since one of the changes of day 25 "adds initial transaltions for over 30 languages" (commit aebccb25f60093c4b2f7deccac0a91c0435b0902) no longer works for me. If I go back to the previous change, it works correctly. I have Winodws 10, I'm not an expert but I already tried reinstalling some libraries involved as well as assigning their location to the path. Thank you
![error1 aebccb25f60093c4b2f7deccac0a91c0435b0902](https://github.com/ramonvc/freegpt-webui/assets/140859511/5a5d00a1-d5b2-412a-9d79-5bd0e6a9965f)
![error2](https://github.com/ramonvc/freegpt-webui/assets/140859511/1e0a4b2f-4936-4369-9957-5ec81374ffa1)

**Comment by ramonvc** [comment]
Did you install the new dependencies?

run again
`pip install -r requirements.txt`

**Comment by LeCarts** [comment]
Yes, I mentioned it in the mail, I ran it several times. I also deleted everything and cloned again.
