### ISSUE TITLE
 FileNotFoundError: [WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by MackyCoders** [ramonvc/freegpt-webui#155]
I literally ran: "pip install -r requirements.txt" in the freegpt-webui folder (cuz i know Python) but it doesnt work
here is a photo of it:
![wth](https://github.com/ramonvc/freegpt-webui/assets/140414476/f082a1fc-9d77-4d2d-8b15-42a022665745)

**Comment by ramonvc** [comment]
Is Flask Babel installed?

`pip install Flask-Babel`

**Comment by MackyCoders** [comment]
oh

**Comment by MackyCoders** [comment]
@ramonvc same thing

**Comment by ramonvc** [comment]
In babel.py, comment out the line `compile_translations()` 

run `pybabel compile -d translations` in project folder

and try again.

![image](https://github.com/ramonvc/freegpt-webui/assets/13617054/93c467e7-7fa2-4c7d-a9b8-1c77b8557cb0)

**Comment by MackyCoders** [comment]
@ramonvc Thx it worked
