### ISSUE TITLE
claude and liama is over?

### ISSUE THREAD

**Issue by DeAlexPesh** [ramonvc/freegpt-webui#160]
![image](https://github.com/ramonvc/freegpt-webui/assets/16735261/d507b253-69fd-4c98-bf6a-5617c6743e93)

**Comment by DeAlexPesh** [comment]
Claude work in this project without proxy... and auto proxy disabled...

**Comment by ramonvc** [comment]
Maybe I'll consider adding the Claude model to the main project.
