### ISSUE TITLE
Can not use GPT-4 model

### ISSUE THREAD

**Issue by j0ole** [ramonvc/freegpt-webui#168]
when I create the docker ok,and then run the docker instance, and then choose GPT-4, it is not the GPT-4 model, I used a very famous prompt "鲁迅和周树人是什么关系“

**Comment by ramonvc** [comment]
As the project demonstrates, models are accessible through various API providers. I can't find out if the provider is using gpt-4 all the time or if it has some kind of failover. However, the user is free to add GPT-4 API providers or other models.

**Comment by j0ole** [comment]
thank u for your response.
