### ISSUE TITLE
After running it on port http://192.168.1.101:1338/chat/ I got these messages

### ISSUE THREAD

**Issue by s-bose7** [ramonvc/freegpt-webui#17]
![bug_freegpt](https://github.com/ramonvc/freegpt-webui/assets/69990740/c1f949a8-2ff3-4b52-a5da-96eb23442dd8)

I got these replies from it, so how do I fix it.

**Comment by zk923852367** [comment]
I have meet same question

**Comment by diegozl** [comment]
This already happened to me. I think it's temporary. Try closing and reopening python.

**Comment by walter-grace** [comment]
<img width="350" alt="Screenshot 2023-06-30 at 8 32 33 AM" src="https://github.com/ramonvc/freegpt-webui/assets/31444892/50824749-1382-45da-9b31-9d2d12654f3b">

I am getting the same error?

**Comment by nkinfe** [comment]
哪个装都是同样的问题，真是致命

**Comment by Cindy723** [comment]
我也是这样 并且切换过代理 依然
