### ISSUE TITLE
Demo doesn't work

### ISSUE THREAD

**Issue by mophisal** [ramonvc/freegpt-webui#174]
All models respond with errors as follows. It's it possible to fix it? Thanks.
![Screenshot_20230805081114](https://github.com/ramonvc/freegpt-webui/assets/11796205/94f0a01d-7f55-4028-8db9-af3b895c20f6)

**Comment by ramonvc** [comment]
This demo needs the ChimeraGPT API Key. You can find all the [demos here](https://github.com/ramonvc/freegpt-webui#project-hosting-and-demonstration-).
