### ISSUE TITLE
image gen

### ISSUE THREAD

**Issue by DeAlexPesh** [ramonvc/freegpt-webui#179]
https://github.com/lllyasviel/Fooocus

**Comment by ramonvc** [comment]
Obrigado. Mas esse é um gerador que usa GPU Nvidia, onde o custo para mante-lo é alto, principalmente utilizando algum serviço em nuvem.

**Comment by ramonvc** [comment]
Thanks. But this is a generator that uses Nvidia GPU, where the cost to maintain it is high, mainly using some cloud service.

**Comment by DeAlexPesh** [comment]
as option. min vram 4Gb. and webui for kandinsky maybe

**Comment by ramonvc** [comment]
kandinsky doesn't need to run locally with GPU, it's much more viable and cheaper
