### ISSUE TITLE
Got this error while using GPT-3.5 and GPT-3.5-turbo-16k

### ISSUE THREAD

**Issue by matheeshapathirana** [ramonvc/freegpt-webui#180]
Got this error while using GPT-3.5 and GPT-3.5-turbo-16k,
```
Using g4f.Provider.Providers.Wewordle provider
Error Occurred::500
```
But GPT-4 working as normal.

**Comment by matheeshapathirana** [comment]
@ramonvc  HELP MEEEEE!

**Comment by ramonvc** [comment]
> Got this error while using GPT-3.5 and GPT-3.5-turbo-16k,
> 
> ```
> Using g4f.Provider.Providers.Wewordle provider
> Error Occurred::500
> ```
> 
> But GPT-4 working as normal.

Most likely the API Provider for these models is offline. You can try changing them or adding new ones.

**Comment by matheeshapathirana** [comment]
Ok, now its working
