### ISSUE TITLE
Unable to chat

### ISSUE THREAD

**Issue by telzhou618** [ramonvc/freegpt-webui#19]
<img width="1154" alt="image" src="https://github.com/ramonvc/freegpt-webui/assets/6360011/71cb056c-960a-4ea1-9d8a-bc03a6f4b4f6">

logs

![image](https://github.com/ramonvc/freegpt-webui/assets/6360011/c8b111bd-0263-4cca-a7f2-d4e8e885a057)

Accessing the address(http://127.0.0.1:1338)  is ok, but receiving message is fail!
sorry，How to solve it？

**Comment by s-bose7** [comment]
This is the same problem I'm facing, I already opened up an issue about it.

**Comment by ramonvc** [comment]
The API provider is unstable. Probably too many requests.
