### ISSUE TITLE
Chimera not work

### ISSUE THREAD

**Issue by NOTIF-API** [ramonvc/freegpt-webui#201]
# when I look at the console you get this error
![изображение_2023-09-10_074634402](https://github.com/ramonvc/freegpt-webui/assets/112265437/811cbf01-2b1c-4402-b3a7-2ab444eaf8f3)
# when I go to the site, no matter where I and my friends are from (we are from different countries)
![изображение_2023-09-10_074808200](https://github.com/ramonvc/freegpt-webui/assets/112265437/6047194b-be6c-4152-9a3d-83f7b8d3a005)

**Comment by wangfeng35** [comment]
ChimeraAI is changed to NagAI.

New website: https://naga.ac/

**Comment by ramonvc** [comment]
Fixed https://github.com/ramonvc/freegpt-webui/commit/859265646f4e750f99c434966390c277a681875f
