### ISSUE TITLE
This API key has been suspended

### ISSUE THREAD

**Issue by WrBug** [ramonvc/freegpt-webui#205]
``` json
{
  "error": {
    "message": "This API key has been suspended. Reason: The account was banned in Discord server\nJoin us: https://discord.naga.ac"
  }
}
```

I cant`t join the discord , what is the reason?
![image](https://github.com/ramonvc/freegpt-webui/assets/12111403/7f7da97e-3b8a-46a7-923b-eff0573c643f)

**Comment by WrBug** [comment]
![image](https://github.com/ramonvc/freegpt-webui/assets/12111403/8ae51a97-eedd-45a6-92eb-c659ccf0301b)

**Comment by WrBug** [comment]
@ramonvc  hello , can you tell me how can I join the discord? Thank you

**Comment by norrybul** [comment]
There's a lot of [free-ai-apis](https://github.com/NovaOSS/free-ai-apis) like NAGA AI which an "on and off" api. Why not support them in the UI (api key and_endpoint) options or instead use [one-api](https://github.com/songquanpeng/one-api) too like [chatgpt-next-web](https://github.com/Yidadaa/ChatGPT-Next-Web). It will be a lot easier supporting g4f inside the app. Thanks.

**Comment by nqf** [comment]
https://github.com/fantasy-peak/cpp-freegpt-webui.git
