### ISSUE TITLE
Fail

### ISSUE THREAD

**Issue by Nukemaster1113** [ramonvc/freegpt-webui#209]
<!doctype html> <html lang=en> <title>500 Internal Server Error</title> <h1>Internal Server Error</h1> <p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>
help

**Comment by nqf** [comment]
> <!doctype html> <title>500 Internal Server Error</title>
> 
> # Internal Server Error
> The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
> 
> 
> help

[maybe you can try this](https://github.com/fantasy-peak/cpp-freegpt-webui.git)
