### ISSUE TITLE
GPT4 cannt work?

### ISSUE THREAD

**Issue by xy-qimu** [ramonvc/freegpt-webui#21]
Can you tell me if the API interface of GPT4 is not available now? Will it also be unavailable in the future?

**Comment by im-fan** [comment]
> Can you tell me if the API interface of GPT4 is not available now? Will it also be unavailable in the future?你能告诉我 GPT4 的 API 接口现在是否不可用吗？将来也会不可用吗？

It can be used, but the agent is gone, you need to open your own agent

**Comment by Bcorw** [comment]
请问这个代理怎么搞

**Comment by ramonvc** [comment]
It started working again with a new Provider.
