### ISSUE TITLE
not work

### ISSUE THREAD

**Issue by wangze0220** [ramonvc/freegpt-webui#27]
![image](https://github.com/ramonvc/freegpt-webui/assets/31640234/120658a0-4929-463f-85a6-c9091283ca90)

**Comment by PTah** [comment]
The same

**Comment by ramonvc** [comment]
API provider is offline. If it doesn't come back soon, I'll change the API Provider.

**Comment by shengkaixuan** [comment]
it stuck 
![图片](https://github.com/ramonvc/freegpt-webui/assets/34889732/8b74fb9a-e840-4757-aa76-2fbb9b69e5ee)

**Comment by ICLXL** [comment]
not working

**Comment by ramonvc** [comment]
Changed API Provider to work again https://github.com/ramonvc/freegpt-webui/commit/b0f8d5164bc5e3fcc7986df9d2b0b288cde97b8f. 

In search of a better Provider
