### ISSUE TITLE
Using Cyrillic causes an error

### ISSUE THREAD

**Issue by Em1tSan** [ramonvc/freegpt-webui#3]
If you use English, everything works, but as soon as you switch to Cyrillic, you get the error shown in the screenshot. 
![image](https://github.com/ramonvc/freegpt-webui/assets/70670181/66e6652b-222a-4eb8-919d-6f5b405c41e1)
![image](https://github.com/ramonvc/freegpt-webui/assets/70670181/1f5363b6-9161-4875-9578-24473d013a85)

**Comment by lucasbr15** [comment]
same

**Comment by ramonvc** [comment]
Hello! Sorry for the delay in responding to this issue. 

I have to confess that I couldn't reproduce the error. 
Can you tell me if it still occurs? 
If so, I will work to resolve it as soon as possible. 

Thank you for your collaboration on the project!

![image](https://github.com/ramonvc/freegpt-webui/assets/13617054/75723ae8-5fb9-48ad-aed0-760ebe03db1d)
