### ISSUE TITLE
Error on uses personalities

### ISSUE THREAD

**Issue by diegozl** [ramonvc/freegpt-webui#4]
Hi,
First of all, congratulations. The tool is incredible.

About the error, I am not able to use the available personalities. When I try, it gives the following error:

`
Error: jailbreak failed. Try again.
`
![ChatGPT (1)](https://github.com/ramonvc/freegpt-webui/assets/52968011/0b104bd5-15e3-49ca-9ddd-fa66006e7d1d)

Tks.

**Comment by ramonvc** [comment]
Thank you for the compliment. I'm happy about it.

I've released a hotfix for that error https://github.com/ramonvc/freegpt-webui/commit/0efc2d51853fe62f42b41c75b8dcb22341aeb868 ,
 I believe it won't happen again now :)
