### ISSUE TITLE
ssl error

### ISSUE THREAD

**Issue by xiaoxiong-12** [ramonvc/freegpt-webui#44]
![7H4@ SMWW1JXXCX$0A8O7$7](https://github.com/ramonvc/freegpt-webui/assets/125569601/99c2968c-0fdb-4de7-93aa-f12ea9f64827)

**Comment by ramonvc** [comment]
It was because of offline API Providers.

Fix in the last commit: https://github.com/ramonvc/freegpt-webui/commit/95ed87776107c905adbb6797ca41c433e6181475
