### ISSUE TITLE
Is the GPT-4 actually a 3.5-turbo?

### ISSUE THREAD

**Issue by Em1tSan** [ramonvc/freegpt-webui#5]
![image](https://github.com/ramonvc/freegpt-webui/assets/70670181/863a4b9d-2154-4145-8dcf-266407bee9a9)

This is the answer sent when you ask about the version.

**Comment by ramonvc** [comment]
This issue of GPT not being able to identify its own version is from OpenAI itself. 
I have access to the official OpenAI GPT-4 32k, and this still happens there.

![image](https://github.com/ramonvc/freegpt-webui/assets/13617054/be5c1f26-6e28-443c-8ddc-30515c1cdd2a)

**Comment by Em1tSan** [comment]
```
            # Generate response
            response = ChatCompletion.create(model=model, stream=True,
                                             messages=messages, provider=g4f.Provider.Forefront)

```
This is a code snippet from file backend.py

If I understand correctly, this is the reason why any request goes to the Forefront provider, regardless of the selected model. This is why when we select GPT-4, we are actually using the same GPT-3.5 Turbo.

If you change the code to 

```
response = ChatCompletion.create(model=model, stream=True,
                                             messages=messages)
```

Then the Provider is taken from the file g4f/__init__.py:

```
class gpt_35_turbo:
        name: str = 'gpt-3.5-turbo'
        base_provider: str = 'openai'
        best_site: Provider.Provider = Provider.Forefront

    class gpt_4:
        name: str = 'gpt-4'
        base_provider: str = 'openai'
        best_site: Provider.Provider = Provider.Bing
```

And now, the request is sent through the Provider Bing. But for some reason it's broken and I couldn't get any response.
