### ISSUE TITLE
[Errno 11001] getaddrinfo failed

### ISSUE THREAD

**Issue by koukou4396** [ramonvc/freegpt-webui#50]
python run.py
Running on http://127.0.0.1:1338
Running on http://192.168.10.5:1338   

I can see the website. But when I type anything, it reads {"_action":"_ask","error":"an error occurred [Errno 11001] getaddrinfo failed","success":false}.

And the cmd reads:
[Errno 11001] getaddrinfo failed

What should I do?

**Comment by ramonvc** [comment]
It was because of offline API Providers.

Fix in the last commit: https://github.com/ramonvc/freegpt-webui/commit/95ed87776107c905adbb6797ca41c433e6181475

**Comment by koukou4396** [comment]
I used the new version. It stays the same.
