### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by gcaddyo** [ramonvc/freegpt-webui#54]
Dear Ramonvc,

We have noticed that your program is accessing our LFG4 API (gpt.free.lsdev.me). On behalf of the LFG4 operations team, we would like to express our gratitude for your recognition.

However, the original intention of creating LFG4 was to provide a free platform for students who cannot afford the cost of PLUS users. Your use of our API consumes a considerable amount of resources, causing difficulties for those who truly need it.

Although we have increased our resources in the past two days, there are still widespread errors. Therefore, we have decided to restrict access for automated programs.

We apologize for any inconvenience this may cause.

Best wishes,
Gavin Wang
2023/07/08

**Comment by ramonvc** [comment]
I understand that the primary goal of LFG4 was to provide a free platform for students who cannot afford the cost of PLUS users. I apologize if my use of the API has consumed a significant amount of resources, causing difficulties for those who truly need it.

I apologize for any inconvenience my usage may have caused.

I appreciate your understanding and would like to inform you that I will promptly remove all requests to the LFG4 API.

Best regards, Ramonvc
