### ISSUE TITLE
Can you support docker in arm64?

### ISSUE THREAD

**Issue by akang943578** [ramonvc/freegpt-webui#63]
Hi there, 

This command not worked on arm64, do you have a plan to support it?
```
docker run -p 1338:1338 ramonvc/freegpt-webui
```
Error:
```
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
```
Platform:
Oracle Cloud Ubuntu 22.04 Arm 64
```
uname -a
Linux instance-20220508-1209-arm1 5.15.0-1034-oracle #40-Ubuntu SMP Wed Apr 19 16:10:04 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux
```

**Comment by pkking** [comment]
@akang943578 Hi, i also pushed a unified test image to `pkking/freegpt-webui:latest`, you can have a try :)

**Comment by hunterlam** [comment]
> @akang943578 Hi, i also pushed a unified test image to `pkking/freegpt-webui:latest`, you can have a try :)嗨，我也推送了统一的测试图片 `pkking/freegpt-webui:latest` 到，大家可以试一试:)

谢谢，已在用
