### ISSUE TITLE
用docker部署 ，问它都是 <!doctype html> <html lang=en> <title>500 Internal Server Error</title> <h1>Internal Server Error</h1> <p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>

### ISSUE THREAD

**Issue by Rontalks** [ramonvc/freegpt-webui#69]
用docker部署 ，问它都是 <!doctype html> <html lang=en> <title>500 Internal Server Error</title> <h1>Internal Server Error</h1> <p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>

**Comment by KamiliaBlow** [comment]
same problem

**Comment by ramonvc** [comment]
GPT-4 **(unstable)**

BTW, it's important to read the [note](https://github.com/ramonvc/freegpt-webui#note-%E2%84%B9%EF%B8%8F) in the readme.
