### ISSUE TITLE
colab with autogpt

### ISSUE THREAD

**Issue by DeAlexPesh** [ramonvc/freegpt-webui#7]
https://github.com/Significant-Gravitas/Auto-GPT

**Comment by diegozl** [comment]
An API is necessary.

**Comment by ramonvc** [comment]
I have thought about integrating the free API with Auto-GPT. I believe it would be a great project to explore. Unfortunately, I don't have time for it now due to work and college. Maybe later :)

**Comment by DeAlexPesh** [comment]
Different AI api: https://github.com/vaibhavk97/Poe
