### ISSUE TITLE
[BUG] There's some bug in my light mode code

### ISSUE THREAD

**Issue by black-fruit** [ramonvc/freegpt-webui#77]
I am trying to fix that

Bug:
1. Because the cookies save the chat history and setting, if my light mode on, after refresh the page, it stay light mode, but button is off, button dead, and I tried to clean cookies, but it isn't working.

**Comment by black-fruit** [comment]
Why not open GPT4 😓

**Comment by ramonvc** [comment]
Fixed in commit https://github.com/ramonvc/freegpt-webui/commit/35716ec63e3b5142f6d98777a2f3c69fd29547b9
