### ISSUE TITLE
Why not open Dev branch

### ISSUE THREAD

**Issue by black-fruit** [ramonvc/freegpt-webui#86]
It's already faster than 5 versions

**Comment by ramonvc** [comment]
> And it support more device.

The backend that was on my site is now public [FreeGPT Chimera](https://github.com/ramonvc/freegpt-webui-chimera).

**Comment by ramonvc** [comment]
> > > And it support more device.
> > 
> > 
> > The backend that was on my site is now public [FreeGPT Chimera](https://github.com/ramonvc/freegpt-webui/tree/chimeragpt-version).
> 
> I didn't find where can get api key

On [ChimereaGPT's Discord](https://discord.gg/Fg2HSJgN). Just type ` /key get` in the bot's chat.
