### ISSUE TITLE
No response from gpt 4 or gpt 3.5

### ISSUE THREAD

**Issue by zhamoytin** [ramonvc/freegpt-webui#9]
I have installed it using Portainer. I can access webui, the model is not responding to my queries
Could you please take a look the below logs and suggest?
https://pastebin.com/RMPNrPFh

**Comment by diegozl** [comment]
> I have installed it using Portainer. I can access webui, the model is not responding to my queries Could you please take a look the below logs and suggest? https://pastebin.com/RMPNrPFh

I'm also not receiving any responses from this GPT today. Most likely a temporary issue.

**Comment by diegozl** [comment]
It returned!
