### ISSUE TITLE
Expose backend as HTTP API for synergy with other projects

### ISSUE THREAD

**Issue by hycxnas** [ramonvc/freegpt-webui#93]
Hi @ramonvc,

I'm a big fan of the freegpt-webui project! I've been using it for a few weeks now, and I'm really impressed with how well it works.

I was wondering if there's any chance that we could expose the access to the backend as an API serving on HTTP (in a form like https://127.0.0.1/api/v1/completions) . I think this would be really useful for enabling synergy with other projects, such as Immersive Translate.

Thanks for your consideration!

**Comment by ramonvc** [comment]
> Hi @ramonvc,
> 
> I'm a big fan of the freegpt-webui project! I've been using it for a few weeks now, and I'm really impressed with how well it works.
> 
> I was wondering if there's any chance that we could expose the access to the backend as an API serving on HTTP (in a form like https://127.0.0.1/api/v1/completions) . I think this would be really useful for enabling synergy with other projects, such as Immersive Translate.
> 
> Thanks for your consideration!

Hi @hycxnas,

Currently, for the Dev project backend, I am utilizing this free API: [Chimera GPT](https://chimeragpt.adventblocks.cc/)
which requires generating an API token on Discord. 
It has a daily limit of 2k requests for the GPT-4 model, which I believe is an excellent threshold for smaller projects. Within this API, you will find the Claude AI and image generator models.

I'm glad you're a fan of the project, and I hope you find the API useful. If you have any questions, feel free to reach out to me on Chimera's Discord chat :)

**Comment by ramonvc** [comment]
> Hi @ramonvc,
> 
> I'm a big fan of the freegpt-webui project! I've been using it for a few weeks now, and I'm really impressed with how well it works.
> 
> I was wondering if there's any chance that we could expose the access to the backend as an API serving on HTTP (in a form like https://127.0.0.1/api/v1/completions) . I think this would be really useful for enabling synergy with other projects, such as Immersive Translate.
> 
> Thanks for your consideration!

The backend that was on my site is now public [FreeGPT Chimera](https://github.com/ramonvc/freegpt-webui-chimera).

**Comment by hycxnas** [comment]
Hi @ramonvc,

Thanks for your update and contribution! 

Chimera and this project? I'd definitely try this wonderful synergy out!
